Set-Alias ls "ls"
Set-Alias ll "ls -lah"
Set-Alias cll "Clear-Host; ls -lah"
Set-Alias dev "Set-Location $env:DEV"
Set-Alias proj "Set-Location $env:DEV\projects"
Set-Alias proj "Set-Location $env:DEV\projects"